obj = pd.Series(range(4), index=list('dabc'))
obj
obj.sort_index()
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])
frame
frame.sort_index
frame.sort_index()
frame.sort_index(axis='columns')
frame.sort_index(axis='columns').sort_index()
frame.sort_index(axis=1, ascending=False)
obj.sort_values()
obj = pd.Series([4, 7, -3, 2])
obj
obj.sort_values()
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame
frame.sort_values(by=['b'])
frame.sort_values(by=['a', 'b'])
frame.sort_index(axis=1).sort_values(by=['a', 'b'])
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()
obj.rank(method='first')
obj.rank(method='last')
obj.rank(ascending=False, method='max')
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame.rank(axis=1)
frame.sort_index(axis=1).rank(axis=1)
frame.sort_index(axis=1).rank(axis=2)
frame.sort_index(axis=1).rank(axis=0)
frame.sort_index(axis=1).rank(axis=0, method='first')
frame.sort_index(axis=1).rank(axis=0, method='min')
frame.sort_index(axis=1).rank(axis=0, method='dense')
